# Generated by Django 5.2.3 on 2025-06-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0002_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('politics', 'Politics'), ('sports', 'Sports'), ('entertainment', 'Entertainment'), ('technology', 'Technology'), ('health', 'Health'), ('business', 'Business')], default='politics', max_length=20),
        ),
    ]
