# Generated by Django 5.2.3 on 2025-06-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('so', 'Somali'), ('sw', 'Kiswahili')], default='en', max_length=2),
        ),
    ]
