# Generated by Django 5.2.3 on 2025-06-22 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0004_alter_article_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='original_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='translations', to='newsapi.article'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['original_article'], name='newsapi_art_origina_3d9af7_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['language'], name='newsapi_art_languag_37d99c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='newsapi_art_categor_f544ec_idx'),
        ),
    ]
