# Generated by Django 5.2.3 on 2025-06-22 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0005_alter_article_options_article_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='newsapi_art_origina_3d9af7_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='newsapi_art_languag_37d99c_idx',
        ),
        migrations.RemoveIndex(
            model_name='article',
            name='newsapi_art_categor_f544ec_idx',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AlterField(
            model_name='article',
            name='original_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapi.article'),
        ),
    ]
