# Generated by Django 5.2.3 on 2025-08-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapi', '0006_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
