services:
  - type: static
    name: news-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        headers:
          - key: Cache-Control
            value: no-cache